name: CustomMobDrops
api-version: 1.15
version: 0.2.0
author: shantek.io
main: io.shantek.CustomMobDrops

commands:
  custommobdrops:
    description: Main command for managing custom mob drops.
    usage: /custommobdrops [reload | enable | disable | list]
    aliases: [drops]
    subcommands:
      reload:
        description: Used to reload the plugin
        usage: /custommobdrops reload
      enable:
        description: Enable custom drops
        usage: /custommobdrops enable
      disable:
        description: Disable custom drops
        usage: /custommobdrops disable
      list:
        description: List mobs with custom drops
        usage: /custommobdrops list

permissions:
  shantek.custommobdrops.reload:
    description: Allows the player to reload the plugin
    default: op
  shantek.custommobdrops.enable:
    description: Allows the player to enable or disable custom drops
    default: op
